fix: Correct soundness bug in keccak circuit
privacy-scaling-explorations/zkevm-circuits pull request #1019
Opened 2023-01-02 09:16 UTC by CPerezz

Once Keccak was migrated to the Challenge API in #925, there was a column containing `data_rlcs` which was getting stored values that were the result of an RLC.

Therefore, this swaps the `data_rlcs` colum Phase to `SecondPhase`.

Resolves: #1016

2023-01-02 16:10 UTC, ed255 requested changes

2023-01-02 16:10 UTC, ed255 commented on zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs
> +    pub(crate) fn query_cell_at_pos<P: Phase>(
It's not clear to me that this function will always return a cell belonging to a column at `phase`. Notice the path when `column_idx < self.columns.len()`, the `phase` parameter is ignored, and we don't know which is the phase of `self.columns[column_idx]`.

AFAIK, the cell manager here returns cells in this order (assume height = 3)

| Col1 | Col2 | Col3 |
| ---- | ---- | ---- |
| 0    | 3    | 6    |
| 1    | 4    | 7    |
| 2    | 5    | 8    |

The queries 0, 3 and 6 cause the `meta.advice_column_in(phase)`.   And the rest of the queries will reuse the column at whichever phase was chosen before.

I think the cell manager needs to be duplicated.  One cell manager for phase1, one cell manager for phase2.  Each one will create columns in the corresponding phase.

2023-01-02 16:13 UTC, ed255 commented on zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs
> +    pub(crate) fn query_cell_at_pos<P: Phase>(
> It's not clear to me that this function will always return a cell belonging to a column at `phase`. Notice the path when `column_idx < self.columns.len()`, the `phase` parameter is ignored, and we don't know which is the phase of `self.columns[column_idx]`.
> 
> AFAIK, the cell manager here returns cells in this order (assume height = 3)
> Col1 	Col2 	Col3
> 0 	3 	6
> 1 	4 	7
> 2 	5 	8
> 
> The queries 0, 3 and 6 cause the `meta.advice_column_in(phase)`. And the rest of the queries will reuse the column at whichever phase was chosen before.
> 
> I think the cell manager needs to be duplicated. One cell manager for phase1, one cell manager for phase2. Each one will create columns in the corresponding phase. And then cells for `data_rlcs` will be allocated with `cell_manager_phase2.query_cell(meta)`, where as the rest of the cells will be queried with `cell_manager_phase1.query_cell(meta)`.

2023-01-17 00:07 UTC, lispc commented
Hi @CPerezz is the pr (almost) done？we may consider directly pick this patch to our fork to make a super circuit with real non mock challenge api

2023-01-17 07:35 UTC, CPerezz commented
@lispc indeed this work was left aside as it implies a significant refactor. And we prefer to pospone it until we have the hi-lo specs ready.
So that we can evaluate how worth is to update this or refactor specs directly.

The issue in here is that duplicating the cellmanager isn't enough. THerefore we need to make deep changes on how the circuit is coded to allow this to work propperly.

2023-01-23 16:05 UTC, ed255 commented
I've added the `wontfix` label following this comment https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1016#issuecomment-1372100536

2023-03-02 12:20 UTC, closed without merging

2023-03-02 12:20 UTC, aguzmant103 commented
Closed in favor a future PR that Scroll team will send