Challenge API for Public Input circuit
privacy-scaling-explorations/zkevm-circuits pull request #1095
Opened 2023-01-20 16:51 UTC by davidnevadoc

Adapts PI circuit to challenge API.
The only change needed is to switch some columns to `SecondPhase` since they are copied from tables that are assigned in the `SecondPhase`.
Resolves #854

2023-01-24 14:47 UTC, CPerezz requested changes

2023-01-24 14:47 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let is_final = meta.advice_column_in(SecondPhase);
Why `is_final` has to be `SecondPhase`? At least the name suggests that it only stores a bool.

2023-01-24 14:47 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let tx_id_inv = meta.advice_column_in(SecondPhase);
This is marked as `SecondPhase` but we never allocate RLC-dependant values here. 
See: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/5ab275565ddd35e7192623f131d0737784f04467/zkevm-circuits/src/pi_circuit.rs#L622L627 where always a Field Element is assigned. And it never carries RLC-related data

2023-01-24 14:47 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let tx_value_inv = meta.advice_column_in(SecondPhase);
Ditto. See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/5ab275565ddd35e7192623f131d0737784f04467/zkevm-circuits/src/pi_circuit.rs#L630-L631

2023-01-24 14:47 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let tx_id_diff_inv = meta.advice_column_in(SecondPhase);
Ditto. https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/5ab275565ddd35e7192623f131d0737784f04467/zkevm-circuits/src/pi_circuit.rs#L771

2023-01-24 14:47 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let is_final = meta.advice_column_in(SecondPhase);
Indeed, I checked and that's the case. No rlc-dependant data is assigned to it.

2023-01-25 10:04 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let is_final = meta.advice_column_in(SecondPhase);
If there's no RLC involved, they should be `FirstPhase` as the values of the witness will be used to compute a commitment that would serve as randomness for the RLCs. 
So we have to include ALL the witness that aren't RLC-related as `FirstPhase`

2023-01-25 10:33 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let tx_id_inv = meta.advice_column_in(SecondPhase);
Exactly. This is the expected usage indeed.

2023-01-25 10:34 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let tx_value_inv = meta.advice_column_in(SecondPhase);
Ohh I see! The `tx_value` variable is holding the RLC already!! That makes sense! Ignore this then.

2023-01-25 10:34 UTC, CPerezz commented on zkevm-circuits/src/pi_circuit.rs
> +        let tx_id_diff_inv = meta.advice_column_in(SecondPhase);
ditto

2023-01-25 11:38 UTC, CPerezz approved these changes
LGTM!

2023-01-25 14:48 UTC, ed255 approved these changes
LGTM!

2023-01-25 16:05 UTC, merged