fix:  misused `max_priority_fee_per_gas` and `max_fee_per_gas`
privacy-scaling-explorations/zkevm-circuits pull request #1559
Opened 2023-08-09 16:57 UTC by dyxushuai

2023-08-09 22:08 UTC, ChihChengLiang commented
Hi @dyxushuai, please add the PR description. It should describe the motivation behind the change.

2023-08-10 08:30 UTC, dyxushuai commented
@ChihChengLiang I have made the changes. Please look over once more.

2023-08-10 08:52 UTC, ChihChengLiang requested changes
Thanks for updating the PR description. It now makes more sense.
I noticed typos on variables. Can you fix them?

2023-08-10 08:52 UTC, ChihChengLiang commented on eth-types/src/geth_types.rs
> +            max_fee_per_gas: Some(tx.gas_cap_cap),
```suggestion
            max_fee_per_gas: Some(tx.gas_fee_cap),
```

2023-08-10 08:52 UTC, ChihChengLiang commented on eth-types/src/geth_types.rs
> +            gas_cap_cap: tx.max_fee_per_gas.unwrap_or_default(),
```suggestion
            gas_fee_cap: tx.max_fee_per_gas.unwrap_or_default(),
```

2023-08-10 12:24 UTC, dyxushuai commented
> Thanks for updating the PR description. It now makes more sense. I noticed typos on variables. Can you fix them?

Sorry, I edited it in browser without testing. Thank you for pointing out

2023-08-10 17:21 UTC, ChihChengLiang approved these changes
LGTM. Thank you for the fix!

2023-08-11 02:20 UTC, hero78119 approved these changes
LGTM! thanks for the fix

2023-08-11 02:22 UTC, merged