StepRws in EVM circuits
privacy-scaling-explorations/zkevm-circuits pull request #1616
Opened 2023-09-19 13:54 UTC by nullity00

### Description

Similar to #1582 , We use the ``StepRws`` struct to automatically track read-write indices.

### Issue Link

#1586 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

The change has been made to the following files

- [x] -  create.rs
- [ ] -  end_tx.rs
- [ ] -  error_oog_call.rs
- [ ] -  error_oog_memory_copy.rs
- [ ] -  error_oog_sload_sstore.rs
- [ ] -  error_return_data_oo_bound.rs
- [ ] -  error_write_protection.rs
- [ ] -  extcodecopy.rs
- [ ] -  extcodehash.rs
- [ ] -  extcodesize.rs
- [ ] -  logs.rs
- [ ] -  return_revert.rs
- [ ] -  returndatacopy.rs
- [ ] -  sha3.rs
- [ ] -  sload.rs
- [ ] -  sstore.rs

### How Has This Been Tested?
On running ``make test-all``, any tests related to the EVM circuit does not fail

2023-09-20 11:03 UTC, ChihChengLiang requested changes
Hi @nullity00,
Thanks for taking this issue! I did the first found of review and left some comments. Please take a look.

2023-09-20 11:03 UTC, ChihChengLiang commented on zkevm-circuits/src/evm_circuit/execution/create.rs
> +                rws.offset_add(5 - transfer_offset); // rw_off + 13 + 5 + copy_rw_increase - transfer_offset
Don't think this is required.
```suggestion
```

2023-09-28 09:42 UTC, ChihChengLiang commented
Hi @nullity00, do you see any blocker in this PR? Is there anything we can help?

Note that you can use `block.debug_print_txs_steps_rw_ops();` to debug the read-writes, as #1586 describes.

2023-11-02 09:39 UTC, ed255 commented
Closing due to inactivity.  @nullity00 if you would like to retake this let us know and we can open the PR again :)

2023-11-02 09:39 UTC, closed without merging