Add bench for copy circuit
privacy-scaling-explorations/zkevm-circuits pull request #899
Opened 2022-11-11 13:02 UTC by smtmfft

Benchmark test case for copy circuit.
Address the last one of #666

2022-11-17 18:25 UTC, Brechtpd commented
When running with `DEGREE > 14` I get

```
thread 'copy_circuit::tests::bench_copy_circuit_prover' panicked at 'total_rws + 1 <= max_rws, total_rws=14909, max_rws=8192', bus-mapping/src/circuit_input_builder.rs:207:13
```

When running with `DEGREE < 14` I get an `NotEnoughRowsAvailable` error. Is `14` the minimum supported degree of the circuit?

2022-11-18 04:20 UTC, smtmfft commented
For degree < 14 maybe yes, I remember it failed even only 1 copy event (will double check). but for degree > 14, no, it is just limited by the CircuitsParams, I forgot to make it grow with the degree. Will fix soon.

2022-11-18 04:54 UTC, smtmfft commented
Fixed, now the degree >10 works fine.

2022-11-21 16:35 UTC, Brechtpd approved these changes

2022-11-30 12:20 UTC, CPerezz requested changes
1st, thanks for the work on adding benchmarks for the copy circuit.
The doc comments included for the CopyCircuit aren't acceptable.

Please, take just 30 more seconds to put them propperly. Then this work can be merged!

2022-12-01 06:15 UTC, smtmfft commented on zkevm-circuits/src/copy_circuit.rs
> +        /// get randomness
Sure. Fixed!

2022-12-01 08:21 UTC, CPerezz approved these changes
I was going to say that the `randomness` should be replaced by the `Challenges`. 
But I see that's already another issue at https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/955.

So let's just approve this!

2022-12-01 09:34 UTC, smtmfft commented
Thanks! Not sure if that #955 will be done by copy_circuit writer, if not, we can do that later.

2022-12-01 11:57 UTC, merged