CopyCircuit Challenge API integration
privacy-scaling-explorations/zkevm-circuits pull request #965
Opened 2022-12-05 15:49 UTC by CPerezz

The CopyCircuit was not using the Value API for witness assignation.
Therefore, the Challenge API has been integrated in both `configure` and
`synthesize` steps and the `Value<F>` is the default operand.

Resolves: #955

2022-12-05 19:26 UTC, roynalnaruto approved these changes
Looks good to me

2022-12-07 10:21 UTC, ed255 requested changes
I believe I found two columns that should be in SecondPhase but are still in FirstPhase.  Please take a look!

2022-12-07 10:21 UTC, ed255 commented on zkevm-circuits/src/table.rs
> +                number_or_hash_to_field(&copy_event.src_id, challenges.evm_word())
The `id` field can contain a hash (code_hash) when the copy is from or to bytecode.  And hash is an RLC of a word.  So I think the `id` should also be `SecondPhase`

2022-12-07 10:21 UTC, ed255 commented on zkevm-circuits/src/copy_circuit.rs
>          let q_step = meta.complex_selector();
When the dest is `CopyDataType::RlcAcc`, the write step contains an RLC, so `value` should also be `SecondPhase`.
See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/56642adc9e9206ef38e3e4dc141192f0fce5eba0/zkevm-circuits/src/table.rs#L990-L996

2022-12-07 10:21 UTC, ed255 commented on zkevm-circuits/src/copy_circuit.rs
> +            // TODO: RW table can't be passed `Challenges<Value<F>>` until the EVM circuit
Let me reference this issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/659 so that we don't forget about this.

2022-12-07 15:31 UTC, ed255 approved these changes
LGTM!

2022-12-07 15:34 UTC, merged